import os

os.system("mkdir mrp_account_link/static/")
os.system("mkdir mrp_account_link/static/description/")
os.system("touch mrp_account_link/static/description/index.html")
os.system("mkdir mrp_account_link/static/src/")
os.system("mkdir mrp_account_link/static/src/css/")
os.system("mkdir mrp_account_link/static/src/img/")
os.system("mkdir mrp_account_link/static/src/js/")
os.system("mkdir mrp_account_link/static/src/xml/")
os.system("mkdir mrp_account_variation/static/")
os.system("mkdir mrp_account_variation/static/description/")
os.system("touch mrp_account_variation/static/description/index.html")
os.system("mkdir mrp_account_variation/static/src/")
os.system("mkdir mrp_account_variation/static/src/css/")
os.system("mkdir mrp_account_variation/static/src/img/")
os.system("mkdir mrp_account_variation/static/src/js/")
os.system("mkdir mrp_account_variation/static/src/xml/")
os.system("mkdir mrp_account_variation_cancel/static/")
os.system("mkdir mrp_account_variation_cancel/static/description/")
os.system("touch mrp_account_variation_cancel/static/description/index.html")
os.system("mkdir mrp_account_variation_cancel/static/src/")
os.system("mkdir mrp_account_variation_cancel/static/src/css/")
os.system("mkdir mrp_account_variation_cancel/static/src/img/")
os.system("mkdir mrp_account_variation_cancel/static/src/js/")
os.system("mkdir mrp_account_variation_cancel/static/src/xml/")
os.system("mkdir mrp_advance/static/")
os.system("mkdir mrp_advance/static/description/")
os.system("touch mrp_advance/static/description/index.html")
os.system("mkdir mrp_advance/static/src/")
os.system("mkdir mrp_advance/static/src/css/")
os.system("mkdir mrp_advance/static/src/img/")
os.system("mkdir mrp_advance/static/src/js/")
os.system("mkdir mrp_advance/static/src/xml/")
os.system("mkdir mrp_bom_constraint/static/")
os.system("mkdir mrp_bom_constraint/static/description/")
os.system("touch mrp_bom_constraint/static/description/index.html")
os.system("mkdir mrp_bom_constraint/static/src/")
os.system("mkdir mrp_bom_constraint/static/src/css/")
os.system("mkdir mrp_bom_constraint/static/src/img/")
os.system("mkdir mrp_bom_constraint/static/src/js/")
os.system("mkdir mrp_bom_constraint/static/src/xml/")
os.system("mkdir mrp_bom_fix_date/static/")
os.system("mkdir mrp_bom_fix_date/static/description/")
os.system("touch mrp_bom_fix_date/static/description/index.html")
os.system("mkdir mrp_bom_fix_date/static/src/")
os.system("mkdir mrp_bom_fix_date/static/src/css/")
os.system("mkdir mrp_bom_fix_date/static/src/img/")
os.system("mkdir mrp_bom_fix_date/static/src/js/")
os.system("mkdir mrp_bom_fix_date/static/src/xml/")
os.system("mkdir mrp_bom_standard_price/static/")
os.system("mkdir mrp_bom_standard_price/static/description/")
os.system("touch mrp_bom_standard_price/static/description/index.html")
os.system("mkdir mrp_bom_standard_price/static/src/")
os.system("mkdir mrp_bom_standard_price/static/src/css/")
os.system("mkdir mrp_bom_standard_price/static/src/img/")
os.system("mkdir mrp_bom_standard_price/static/src/js/")
os.system("mkdir mrp_bom_standard_price/static/src/xml/")
os.system("mkdir mrp_bom_subproduct_cost/static/")
os.system("mkdir mrp_bom_subproduct_cost/static/description/")
os.system("touch mrp_bom_subproduct_cost/static/description/index.html")
os.system("mkdir mrp_bom_subproduct_cost/static/src/")
os.system("mkdir mrp_bom_subproduct_cost/static/src/css/")
os.system("mkdir mrp_bom_subproduct_cost/static/src/img/")
os.system("mkdir mrp_bom_subproduct_cost/static/src/js/")
os.system("mkdir mrp_bom_subproduct_cost/static/src/xml/")
os.system("mkdir mrp_consume_produce/static/")
os.system("mkdir mrp_consume_produce/static/description/")
os.system("touch mrp_consume_produce/static/description/index.html")
os.system("mkdir mrp_consume_produce/static/src/")
os.system("mkdir mrp_consume_produce/static/src/css/")
os.system("mkdir mrp_consume_produce/static/src/img/")
os.system("mkdir mrp_consume_produce/static/src/js/")
os.system("mkdir mrp_consume_produce/static/src/xml/")
os.system("mkdir mrp_default_location/static/")
os.system("mkdir mrp_default_location/static/description/")
os.system("touch mrp_default_location/static/description/index.html")
os.system("mkdir mrp_default_location/static/src/")
os.system("mkdir mrp_default_location/static/src/css/")
os.system("mkdir mrp_default_location/static/src/img/")
os.system("mkdir mrp_default_location/static/src/js/")
os.system("mkdir mrp_default_location/static/src/xml/")
os.system("mkdir mrp_fix_decimal_production/static/")
os.system("mkdir mrp_fix_decimal_production/static/description/")
os.system("touch mrp_fix_decimal_production/static/description/index.html")
os.system("mkdir mrp_fix_decimal_production/static/src/")
os.system("mkdir mrp_fix_decimal_production/static/src/css/")
os.system("mkdir mrp_fix_decimal_production/static/src/img/")
os.system("mkdir mrp_fix_decimal_production/static/src/js/")
os.system("mkdir mrp_fix_decimal_production/static/src/xml/")
os.system("mkdir mrp_jit_extended/static/")
os.system("mkdir mrp_jit_extended/static/description/")
os.system("touch mrp_jit_extended/static/description/index.html")
os.system("mkdir mrp_jit_extended/static/src/")
os.system("mkdir mrp_jit_extended/static/src/css/")
os.system("mkdir mrp_jit_extended/static/src/img/")
os.system("mkdir mrp_jit_extended/static/src/js/")
os.system("mkdir mrp_jit_extended/static/src/xml/")
os.system("mkdir mrp_location_line_production/static/")
os.system("mkdir mrp_location_line_production/static/description/")
os.system("touch mrp_location_line_production/static/description/index.html")
os.system("mkdir mrp_location_line_production/static/src/")
os.system("mkdir mrp_location_line_production/static/src/css/")
os.system("mkdir mrp_location_line_production/static/src/img/")
os.system("mkdir mrp_location_line_production/static/src/js/")
os.system("mkdir mrp_location_line_production/static/src/xml/")
os.system("mkdir mrp_production_analytic_acc/static/")
os.system("mkdir mrp_production_analytic_acc/static/description/")
os.system("touch mrp_production_analytic_acc/static/description/index.html")
os.system("mkdir mrp_production_analytic_acc/static/src/")
os.system("mkdir mrp_production_analytic_acc/static/src/css/")
os.system("mkdir mrp_production_analytic_acc/static/src/img/")
os.system("mkdir mrp_production_analytic_acc/static/src/js/")
os.system("mkdir mrp_production_analytic_acc/static/src/xml/")
os.system("mkdir mrp_production_bom_related/static/")
os.system("mkdir mrp_production_bom_related/static/description/")
os.system("touch mrp_production_bom_related/static/description/index.html")
os.system("mkdir mrp_production_bom_related/static/src/")
os.system("mkdir mrp_production_bom_related/static/src/css/")
os.system("mkdir mrp_production_bom_related/static/src/img/")
os.system("mkdir mrp_production_bom_related/static/src/js/")
os.system("mkdir mrp_production_bom_related/static/src/xml/")
os.system("mkdir mrp_production_cancel/static/")
os.system("mkdir mrp_production_cancel/static/description/")
os.system("touch mrp_production_cancel/static/description/index.html")
os.system("mkdir mrp_production_cancel/static/src/")
os.system("mkdir mrp_production_cancel/static/src/css/")
os.system("mkdir mrp_production_cancel/static/src/img/")
os.system("mkdir mrp_production_cancel/static/src/js/")
os.system("mkdir mrp_production_cancel/static/src/xml/")
os.system("mkdir mrp_production_filter/static/")
os.system("mkdir mrp_production_filter/static/description/")
os.system("touch mrp_production_filter/static/description/index.html")
os.system("mkdir mrp_production_filter/static/src/")
os.system("mkdir mrp_production_filter/static/src/css/")
os.system("mkdir mrp_production_filter/static/src/img/")
os.system("mkdir mrp_production_filter/static/src/js/")
os.system("mkdir mrp_production_filter/static/src/xml/")
os.system("mkdir mrp_production_filter_date/static/")
os.system("mkdir mrp_production_filter_date/static/description/")
os.system("touch mrp_production_filter_date/static/description/index.html")
os.system("mkdir mrp_production_filter_date/static/src/")
os.system("mkdir mrp_production_filter_date/static/src/css/")
os.system("mkdir mrp_production_filter_date/static/src/img/")
os.system("mkdir mrp_production_filter_date/static/src/js/")
os.system("mkdir mrp_production_filter_date/static/src/xml/")
os.system("mkdir mrp_production_filter_product/static/")
os.system("mkdir mrp_production_filter_product/static/description/")
os.system("touch mrp_production_filter_product/static/description/index.html")
os.system("mkdir mrp_production_filter_product/static/src/")
os.system("mkdir mrp_production_filter_product/static/src/css/")
os.system("mkdir mrp_production_filter_product/static/src/img/")
os.system("mkdir mrp_production_filter_product/static/src/js/")
os.system("mkdir mrp_production_filter_product/static/src/xml/")
os.system("mkdir mrp_production_make_wzd/static/")
os.system("mkdir mrp_production_make_wzd/static/description/")
os.system("touch mrp_production_make_wzd/static/description/index.html")
os.system("mkdir mrp_production_make_wzd/static/src/")
os.system("mkdir mrp_production_make_wzd/static/src/css/")
os.system("mkdir mrp_production_make_wzd/static/src/img/")
os.system("mkdir mrp_production_make_wzd/static/src/js/")
os.system("mkdir mrp_production_make_wzd/static/src/xml/")
os.system("mkdir mrp_production_procurement_order/static/")
os.system("mkdir mrp_production_procurement_order/static/description/")
os.system("touch mrp_production_procurement_order/static/description/index.html")
os.system("mkdir mrp_production_procurement_order/static/src/")
os.system("mkdir mrp_production_procurement_order/static/src/css/")
os.system("mkdir mrp_production_procurement_order/static/src/img/")
os.system("mkdir mrp_production_procurement_order/static/src/js/")
os.system("mkdir mrp_production_procurement_order/static/src/xml/")
os.system("mkdir mrp_production_security_force/static/")
os.system("mkdir mrp_production_security_force/static/description/")
os.system("touch mrp_production_security_force/static/description/index.html")
os.system("mkdir mrp_production_security_force/static/src/")
os.system("mkdir mrp_production_security_force/static/src/css/")
os.system("mkdir mrp_production_security_force/static/src/img/")
os.system("mkdir mrp_production_security_force/static/src/js/")
os.system("mkdir mrp_production_security_force/static/src/xml/")
os.system("mkdir mrp_production_wizard/static/")
os.system("mkdir mrp_production_wizard/static/description/")
os.system("touch mrp_production_wizard/static/description/index.html")
os.system("mkdir mrp_production_wizard/static/src/")
os.system("mkdir mrp_production_wizard/static/src/css/")
os.system("mkdir mrp_production_wizard/static/src/img/")
os.system("mkdir mrp_production_wizard/static/src/js/")
os.system("mkdir mrp_production_wizard/static/src/xml/")
os.system("mkdir mrp_pt_planified/static/")
os.system("mkdir mrp_pt_planified/static/description/")
os.system("touch mrp_pt_planified/static/description/index.html")
os.system("mkdir mrp_pt_planified/static/src/")
os.system("mkdir mrp_pt_planified/static/src/css/")
os.system("mkdir mrp_pt_planified/static/src/img/")
os.system("mkdir mrp_pt_planified/static/src/js/")
os.system("mkdir mrp_pt_planified/static/src/xml/")
os.system("mkdir mrp_request_return/static/")
os.system("mkdir mrp_request_return/static/description/")
os.system("touch mrp_request_return/static/description/index.html")
os.system("mkdir mrp_request_return/static/src/")
os.system("mkdir mrp_request_return/static/src/css/")
os.system("mkdir mrp_request_return/static/src/img/")
os.system("mkdir mrp_request_return/static/src/js/")
os.system("mkdir mrp_request_return/static/src/xml/")
os.system("mkdir mrp_request_return_cancel/static/")
os.system("mkdir mrp_request_return_cancel/static/description/")
os.system("touch mrp_request_return_cancel/static/description/index.html")
os.system("mkdir mrp_request_return_cancel/static/src/")
os.system("mkdir mrp_request_return_cancel/static/src/css/")
os.system("mkdir mrp_request_return_cancel/static/src/img/")
os.system("mkdir mrp_request_return_cancel/static/src/js/")
os.system("mkdir mrp_request_return_cancel/static/src/xml/")
os.system("mkdir mrp_scheduled_onchange_product/static/")
os.system("mkdir mrp_scheduled_onchange_product/static/description/")
os.system("touch mrp_scheduled_onchange_product/static/description/index.html")
os.system("mkdir mrp_scheduled_onchange_product/static/src/")
os.system("mkdir mrp_scheduled_onchange_product/static/src/css/")
os.system("mkdir mrp_scheduled_onchange_product/static/src/img/")
os.system("mkdir mrp_scheduled_onchange_product/static/src/js/")
os.system("mkdir mrp_scheduled_onchange_product/static/src/xml/")
os.system("mkdir mrp_subproduct_pt_planified/static/")
os.system("mkdir mrp_subproduct_pt_planified/static/description/")
os.system("touch mrp_subproduct_pt_planified/static/description/index.html")
os.system("mkdir mrp_subproduct_pt_planified/static/src/")
os.system("mkdir mrp_subproduct_pt_planified/static/src/css/")
os.system("mkdir mrp_subproduct_pt_planified/static/src/img/")
os.system("mkdir mrp_subproduct_pt_planified/static/src/js/")
os.system("mkdir mrp_subproduct_pt_planified/static/src/xml/")
os.system("mkdir mrp_subproduction/static/")
os.system("mkdir mrp_subproduction/static/description/")
os.system("touch mrp_subproduction/static/description/index.html")
os.system("mkdir mrp_subproduction/static/src/")
os.system("mkdir mrp_subproduction/static/src/css/")
os.system("mkdir mrp_subproduction/static/src/img/")
os.system("mkdir mrp_subproduction/static/src/js/")
os.system("mkdir mrp_subproduction/static/src/xml/")
os.system("mkdir mrp_variation/static/")
os.system("mkdir mrp_variation/static/description/")
os.system("touch mrp_variation/static/description/index.html")
os.system("mkdir mrp_variation/static/src/")
os.system("mkdir mrp_variation/static/src/css/")
os.system("mkdir mrp_variation/static/src/img/")
os.system("mkdir mrp_variation/static/src/js/")
os.system("mkdir mrp_variation/static/src/xml/")
os.system("mkdir mrp_webkit_report_wizard/static/")
os.system("mkdir mrp_webkit_report_wizard/static/description/")
os.system("touch mrp_webkit_report_wizard/static/description/index.html")
os.system("mkdir mrp_webkit_report_wizard/static/src/")
os.system("mkdir mrp_webkit_report_wizard/static/src/css/")
os.system("mkdir mrp_webkit_report_wizard/static/src/img/")
os.system("mkdir mrp_webkit_report_wizard/static/src/js/")
os.system("mkdir mrp_webkit_report_wizard/static/src/xml/")
os.system("mkdir mrp_workcenter_management/static/")
os.system("mkdir mrp_workcenter_management/static/description/")
os.system("touch mrp_workcenter_management/static/description/index.html")
os.system("mkdir mrp_workcenter_management/static/src/")
os.system("mkdir mrp_workcenter_management/static/src/css/")
os.system("mkdir mrp_workcenter_management/static/src/img/")
os.system("mkdir mrp_workcenter_management/static/src/js/")
os.system("mkdir mrp_workcenter_management/static/src/xml/")
os.system("mkdir mrp_workcenter_responsible/static/")
os.system("mkdir mrp_workcenter_responsible/static/description/")
os.system("touch mrp_workcenter_responsible/static/description/index.html")
os.system("mkdir mrp_workcenter_responsible/static/src/")
os.system("mkdir mrp_workcenter_responsible/static/src/css/")
os.system("mkdir mrp_workcenter_responsible/static/src/img/")
os.system("mkdir mrp_workcenter_responsible/static/src/js/")
os.system("mkdir mrp_workcenter_responsible/static/src/xml/")

os.system("cp -r icon.png mrp_account_link/static/src/img/")
os.system("cp -r icon.png mrp_account_variation/static/src/img/")
os.system("cp -r icon.png mrp_account_variation_cancel/static/src/img/")
os.system("cp -r icon.png mrp_advance/static/src/img/")
os.system("cp -r icon.png mrp_bom_constraint/static/src/img/")
os.system("cp -r icon.png mrp_bom_fix_date/static/src/img/")
os.system("cp -r icon.png mrp_bom_standard_price/static/src/img/")
os.system("cp -r icon.png mrp_bom_subproduct_cost/static/src/img/")
os.system("cp -r icon.png mrp_consume_produce/static/src/img/")
os.system("cp -r icon.png mrp_default_location/static/src/img/")
os.system("cp -r icon.png mrp_fix_decimal_production/static/src/img/")
os.system("cp -r icon.png mrp_jit_extended/static/src/img/")
os.system("cp -r icon.png mrp_location_line_production/static/src/img/")
os.system("cp -r icon.png mrp_production_analytic_acc/static/src/img/")
os.system("cp -r icon.png mrp_production_bom_related/static/src/img/")
os.system("cp -r icon.png mrp_production_cancel/static/src/img/")
os.system("cp -r icon.png mrp_production_filter/static/src/img/")
os.system("cp -r icon.png mrp_production_filter_date/static/src/img/")
os.system("cp -r icon.png mrp_production_filter_product/static/src/img/")
os.system("cp -r icon.png mrp_production_make_wzd/static/src/img/")
os.system("cp -r icon.png mrp_production_procurement_order/static/src/img/")
os.system("cp -r icon.png mrp_production_security_force/static/src/img/")
os.system("cp -r icon.png mrp_production_wizard/static/src/img/")
os.system("cp -r icon.png mrp_pt_planified/static/src/img/")
os.system("cp -r icon.png mrp_request_return/static/src/img/")
os.system("cp -r icon.png mrp_request_return_cancel/static/src/img/")
os.system("cp -r icon.png mrp_scheduled_onchange_product/static/src/img/")
os.system("cp -r icon.png mrp_subproduction/static/src/img/")
os.system("cp -r icon.png mrp_subproduct_pt_planified/static/src/img/")
os.system("cp -r icon.png mrp_variation/static/src/img/")
os.system("cp -r icon.png mrp_webkit_report_wizard/static/src/img/")
os.system("cp -r icon.png mrp_workcenter_management/static/src/img/")
os.system("cp -r icon.png mrp_workcenter_responsible/static/src/img/")


os.system("cp -r icon.png mrp_request_add_item/static/src/img/")
os.system("cp -r icon.png mrp_button_box/static/src/img/")
os.system("cp -r icon.png mrp_workorder_variation/static/src/img/")
os.system("cp -r icon.png mrp_shipping_packaging/static/src/img/")
